# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech Effects
email: dcohen18@gmail.com
description: a coding blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://scraggo.github.io" # the base hostname & protocol for your site
twitter_username: decguitar
github_username:  scraggo
paginate: 20

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
